---
kind: Service
apiVersion: v1
metadata:
  name: matrix-synapse
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8008
      targetPort: 8008
    - name: https
      protocol: TCP
      port: 8448
      targetPort: 8448
  selector:
    app: matrix-synapse
  type: ClusterIP
---
kind: Secret
apiVersion: v1
metadata:
  name: matrix-synapse-tls
data:
  tls.crt:
  tls.key:
type: kubernetes.io/tls
---
kind: Secret
apiVersion: v1
metadata:
  name: matrix-synapse-tls-dh
data:
  dhparam.pam:
type: Opaque
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: matrix-synapse
  labels:
    app: matrix-synapse
spec:
  selector:
    matchLabels:
      app: matrix-synapse
  template:
    metadata:
      labels:
        app: matrix-synapse
    spec:
      volumes:
        - name: matrix-synapse-data
          emptyDir: {}
        - name: matrix-synapse-tls
          secret:
            secretName: matrix-synapse-tls
        - name: matrix-synapse-tls-dh
          secret:
            secretName: matrix-synapse-tls-dh
      containers:
        - name: matrix-synapse
          image: ananace/matrix-synapse
          imagePullPolicy: Always
          volumeMounts:
            - name: matrix-synapse-data
              mountPath: /var/lib/matrix-synapse/data
            - name: matrix-synapse-tls
              mountPath: /var/lib/matrix-synapse/tls
            - name: matrix-synapse-tls-dh
              mountPath: /var/lib/matrix-synapse/tls_dh
          env:
            - name: SYNAPSE_CACHE_FACTOR
              value: '0.5'
            - name: MATRIX_SERVERNAME
              value: matrix.example.com
            - name: MATRIX_DATABASE
              value: postgres
            - name: MATRIX_DB_USER
              value: synapse
            - name: MATRIX_DB_PASSWORD
              value: synapse
            - name: MATRIX_DB_DATABASE
              value: synapse
            - name: MATRIX_DB_HOST
              value: postgres.example.com
            - name: MATRIX_DB_PORT
              value: '5432'
            - name: MATRIX_LDAPURI
              value: ldap.example.com
            - name: MATRIX_LDAPBASE
              value: ou=Users,dc=example,dc=com
            - name: MATRIX_SIGNKEY
              value: 'ed25519 a_bdji EXAMPLEKEY'
            - name: MATRIX_LDAPUIDATTR
              value: uid
            - name: MATRIX_LDAPMAILATTR
              value: mail
            - name: MATRIX_LDAPNAMEATTR
              value: gecos
          resources:
            request:
              memory: 250Mi
              cpu: 250m
            limits:
              memory: 4Gi
              cpu: 1
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /_matrix/client/versions
              port: 8008
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 5
