---
kind: Service
apiVersion: v1
metadata:
  name: matrix-synapse
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8008
      targetPort: 8008
    - name: https
      protocol: TCP
      port: 8448
      targetPort: 8448
    - name: replication
      protocol: TCP
      port: 9092
      targetPort: 9092
  selector:
    app: matrix-synapse
  type: ClusterIP
---
kind: Secret
apiVersion: v1
metadata:
  name: matrix-synapse-tls
data:
  tls.crt:
  tls.key:
type: kubernetes.io/tls
---
kind: Secret
apiVersion: v1
metadata:
  name: matrix-synapse-tls-dh
data:
  dhparam.pam:
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: matrix-synapse-signing
data:
  signing.key:
type: Opaque
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: matrix-synapse
  labels:
    app: matrix-synapse
spec:
  selector:
    matchLabels:
      app: matrix-synapse
  template:
    metadata:
      labels:
        app: matrix-synapse
    spec:
      volumes:
        - name: matrix-synapse-data
          emptyDir: {}
        - name: matrix-synapse-tls
          secret:
            secretName: matrix-synapse-tls
        - name: matrix-synapse-tls-dh
          secret:
            secretName: matrix-synapse-tls-dh
        - name: matrix-synapse-signing
          secret:
            secretName: matrix-synapse-signing
      containers:
        - name: matrix-synapse
          image: ananace/matrix-synapse:0.25.1-lite
          imagePullPolicy: Always
          volumeMounts:
            - name: matrix-synapse-data
              mountPath: /data
            - name: matrix-synapse-config
              mountPath: /config/extra
            - name: matrix-synapse-tls
              mountPath: /config/tls
            - name: matrix-synapse-tls-dh
              mountPath: /config/tls_dh
            - name: matrix-synapse-signin
              mountPath: /config/signing
          env:
            - name: SYNAPSE_CACHE_FACTOR
              value: '0.5'
          resources:
            request:
              memory: 250Mi
              cpu: 250m
            limits:
              memory: 4Gi
              cpu: 1
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /_matrix/client/versions
              port: 8008
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 5
