---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
  name: matrix-synapse
spec:
  rules:
  - host: kittenface.studio
    http:
      paths:
      ## mxisd support for directory, authentication, and identity
      - backend:
          serviceName: mxisd
          servicePort: 8090
        path: /_matrix/(identity|client/r0/(login|user_directory))

      ## Federation reader worker
      - backend:
          serviceName: federation-reader
          servicePort: 8083
        path: /_matrix/federation/v1/((event|state|state_ids|backfill|get_missing_events|query|make_join|make_leave|send_join|send_leave|invite|query_auth|event_auth|exchange_third_party_invite|send)/|publicRooms)

      ## The remaining traffic goes to Synapse itself
      - backend:
          serviceName: matrix-synapse
          servicePort: 8008
        path: /_matrix/

      ## And if you're feeling like doing something insecure, you can serve a Riot instance on the root.
      #  (Don't do this, put it on a different subdomain instead)
      # - backend:
      #     serviceName: riot
      #     servicePort: 80
      #   path: /
  tls:
  - hosts:
    - kittenface.studio
    secretName: matrix-synapse-tls
