apiVersion: v1
data:
  ma1sd.yaml: |
    matrix:
      domain: example.com
    server:
      name: matrix.example.com
      port: 8090
      publicUrl: https://matrix.example.com

    key:
      # Can be stored in the PVC as well, in which case it will be generated
      path: /etc/ma1sd/signing.key

    storage:
      provider:
        sqlite:
          database: /var/lib/ma1sd/ma1sd.db

    forward:
      servers:
      - matrix.org

    dns:
      overwrite:
        homeserver:
          client:
          - name: matrix.example.com
            value: 'http://matrix-synapse.matrix.svc:8008'
          - name: example.com
            value: 'http://matrix-synapse.matrix.svc:8008'
kind: ConfigMap
metadata:
  labels:
    app: ma1sd
  name: ma1sd-config
  namespace: matrix
---
# Ma1sd uses a signing key as well, while it's possible to reuse the Synapse key
# it's recommended to generate a specific one for ma1sd
kind: Secret
apiVersion: v1
metadata:
  name: ma1sd-keys
data:
  signing.key:
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ma1sd
  name: ma1sd
  namespace: matrix
spec:
  ports:
  - name: ma1sd
    port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    app: ma1sd
  type: ClusterIP
---
# ma1sd stores its database in an sqlite file, which needs a PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ma1sd-data
  namespace: matrix
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ma1sd
  name: ma1sd
  namespace: matrix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ma1sd
  template:
    metadata:
      labels:
        app: ma1sd
    spec:
      containers:
      - image: ma1uta/ma1sd:2.2.2
        imagePullPolicy: IfNotPresent
        name: ma1sd
        readinessProbe:
          tcpSocket:
            port: 8090
        volumeMounts:
        - mountPath: /var/lib/ma1sd
          name: ma1sd-data
        - mountPath: /etc/ma1sd/signing.key
          name: matrix-synapse-keys
          subPath: signing.key
        - mountPath: /etc/ma1sd/ma1sd.yaml
          name: ma1sd-config
          subPath: ma1sd.yaml
      restartPolicy: Always
      volumes:
      - name: ma1sd-data
        persistentVolumeClaim:
          claimName: ma1sd-data
      - name: ma1sd-keys
        secret:
          secretName: ma1sd-keys
      - configMap:
          name: ma1sd-config
        name: ma1sd-config
