---
apiVersion: v1
data:
  config.json: |
    {
        "default_hs_url": "https://matrix.example.com",
        "default_is_url": "https://matrix.org",
        "disable_custom_urls": false,
        "disable_guests": true,
        "disable_login_language_selector": false,
        "disable_3pid_login": false,
        "brand": "Riot",
        "integrations_ui_url": "https://scalar.vector.im/",
        "integrations_rest_url": "https://scalar.vector.im/api",
        "bug_report_endpoint_url": "https://riot.im/bugreports/submit",
        "features": {
            "feature_groups": "labs",
            "feature_pinning": "labs"
        },
        "default_federate": true,
        "welcomePageUrl": "home.html",
        "default_theme": "light",
        "roomDirectory": {
            "servers": [
                "matrix.org"
            ]
        },
        "piwik": {
            "url": "https://piwik.riot.im/",
            "whitelistedHSUrls": ["https://matrix.org"],
            "whitelistedISUrls": ["https://vector.im", "https://matrix.org"],
            "siteId": 1
        },
        "enable_presence_by_hs_url": {
            "https://matrix.org": false
        }
    }
kind: ConfigMap
metadata:
  labels:
    app: riot
  name: riot-config
  namespace: matrix
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: riot
  name: riot
  namespace: matrix
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: riot
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: riot
  name: riot
  namespace: matrix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: riot
  template:
    metadata:
      labels:
        app: riot
    spec:
      containers:
      - image: bubuntux/riot-web
        imagePullPolicy: Always
        name: riot-web
        readinessProbe:
          tcpSocket:
            port: 80
        volumeMounts:
        - mountPath: /etc/riot-web/config.json
          name: riot-config
          subPath: config.json
      restartPolicy: Always
      volumes:
      - configMap:
          defaultMode: 420
          name: riot-config
        name: riot-config
