name: ci

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  repository_dispatch:
    types: [synapse-build-successful]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      -
        name: Cache Docker layers
        uses: actions/cache@v2.1.6
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - uses: docker/setup-buildx-action@v1.4.1

      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1.9.0 
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_USERNAME }}
          password: ${{ secrets.CR_PAT }}

      -
        name: Build and push
        uses: docker/build-push-action@v2.4.0
        with:
          push: true
          tags: |
            ghcr.io/mqsdk/synapse-kubernetes:latest
            ghcr.io/mqsdk/synapse-kubernetes:${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          file: Dockerfile
